// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn92Hy7gZOW_DrMwlVBp_kgbfQJZKzc1s',
    appId: '1:1048855205536:web:291d32c83c3dbfce7adbc5',
    messagingSenderId: '1048855205536',
    projectId: 'claa-49961',
    authDomain: 'claa-49961.firebaseapp.com',
    storageBucket: 'claa-49961.firebasestorage.app',
    measurementId: 'G-824BXDHEY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznOF9A33qjo1JHEbJQZvqHw1u0_OITo4',
    appId: '1:1048855205536:android:0f442dd2ed2f61f57adbc5',
    messagingSenderId: '1048855205536',
    projectId: 'claa-49961',
    storageBucket: 'claa-49961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUSPsYFuMwC2MiZH7c81Amc9Xg9p9ik8c',
    appId: '1:1048855205536:ios:a4f0c93fbe0dcf377adbc5',
    messagingSenderId: '1048855205536',
    projectId: 'claa-49961',
    storageBucket: 'claa-49961.firebasestorage.app',
    iosClientId: '1048855205536-aufb1963ems2vf90n9uvl9hn1ravo9dh.apps.googleusercontent.com',
    iosBundleId: 'com.tylerbarnes.claa',
  );
}
